In [1]:
from sklearn import preprocessing

In [2]:
import numpy as np

In [5]:
a=np.array([[10,2.7,3.6],
          [-100,5,-2],
          [120,20,40]],dtype=np.float64)

In [6]:
print(a)

[[  10.     2.7    3.6]
 [-100.     5.    -2. ]
 [ 120.    20.    40. ]]


In [7]:
print(preprocessing.scale(a))#将a标准化

[[ 0.         -0.85170713 -0.55138018]
 [-1.22474487 -0.55187146 -0.852133  ]
 [ 1.22474487  1.40357859  1.40351318]]
